BOARD_TAG    = leonardo
ISP_PROG     = gpio
ISP_PORT     = /dev/ttyACM0
MONITOR_PORT = /dev/ttyACM0
AVRDUDE      = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf

ARDUINO_LIBS = SHT1x
USER_LIB_PATH = ../libs

include /usr/share/arduino/Arduino.mk
