BOARD_TAG    = uno
ISP_PROG     = gpio
ISP_PORT     = /dev/ttyACM0
MONITOR_PORT = /dev/ttyACM0
AVRDUDE      = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf

ARDUINO_LIBS = Wire BMP180
USER_LIB_PATH = ../libs

include /usr/share/arduino/Arduino.mk
